// Builds every generated brand asset: SVG source in the repo, PNG for posting.
//
//   npm run social-cards
//
//   assets/social/grainlify-launch-*        1200x675 / 1200x627   share cards
//   assets/social/grainlify-early-access-*  1200x675 / 1200x627   campaign cards
//   assets/social/grainlify-banner-*        1500x500 / 1128x191   profile banners
//   assets/social/grainlify-avatar-*        400x400               profile pictures
//
// Five properties this script exists to hold, none of which survive a
// hand-exported image:
//
//   1. Every colour is read from src/styles/brand.css at build time. No hex is
//      typed in this directory. Change the palette there and re-run; the assets
//      follow. If a role's token disappears, the build fails rather than
//      quietly falling back to a default.
//   2. Every text/background pair is measured for WCAG AA contrast and the
//      build FAILS on a failure. White-on-gold measured 2.61 in the light-mode
//      audit - a pair that looked fine and was not - so "check the contrast"
//      is a gate here, not a note in a comment.
//   3. Every drawn element is measured after rendering, in the real font, and
//      the build fails if it crosses a safe edge. A standalone SVG does not
//      wrap or shrink text: an over-long line runs off the asset silently.
//   4. Banners additionally clear the profile-picture overlay, and avatars
//      clear the circular crop. Both are places where an asset is not merely
//      tight but actively covered, and neither is visible in the flat file.
//   5. The campaign card is verified at feed-thumbnail width by counting the
//      display number's actual painted pixels, because that is the size most
//      impressions of it are seen at and a card that only works at 1200px
//      does not work.
//
// The copy lives in content.mjs. This file holds no words of its own.

import { writeFileSync, mkdirSync, rmSync } from 'node:fs'
import path from 'node:path'
import sharp from 'sharp'
import { chromium } from '@playwright/test'

import {
  AVATARS,
  BANNER_CONTENT,
  BANNERS,
  CAMPAIGN_CONTENT,
  CAMPAIGNS,
  CONTENT,
  ROLES,
  SIZES,
} from './content.mjs'
import {
  auditContrast,
  compositeOver,
  esc,
  FONT_IMPORT,
  FONT_STACK,
  logo,
  renderOne,
  reportProblems,
  repoRoot,
  resolvePalette,
} from './lib.mjs'

const outDir = path.join(repoRoot, 'assets', 'social')
mkdirSync(outDir, { recursive: true })

const C = resolvePalette(ROLES, 'all generated assets')

const GENERATED_BY = `  <!-- Generated by scripts/social-cards/build.mjs. Do not edit by hand:
       edit scripts/social-cards/content.mjs and re-run \`npm run social-cards\`.
       Colours are read from src/styles/brand.css at build time. -->`

/** The lockup: real mark path, scaled from the asset's own viewBox, plus the
 *  wordmark optically centred on the mark rather than sharing its baseline. */
function lockup({ x, y, logoSize, wordmarkSize, markFill, wordFill, gap = 14 }) {
  const scale = logoSize / logo.vbH
  const logoW = (logoSize * logo.vbW) / logo.vbH
  return `    <g transform="translate(${x}, ${y}) scale(${scale.toFixed(5)})">
      <path d="${logo.path}" fill="${markFill}"/>
    </g>
    <text class="wordmark" x="${x + logoW + gap}" y="${y + logoSize / 2}" dominant-baseline="central" fill="${wordFill}">${esc(BANNER_CONTENT.wordmark)}</text>`
}

// ===========================================================================
// 1. Share cards
// ===========================================================================

function buildCardSvg(size) {
  const { width, height, margin } = size

  const headline = CONTENT.headline
    .map((line, i) => {
      const y = size.headline.firstBaseline + i * size.headline.lineHeight
      return `    <text class="headline" x="${margin}" y="${y}" fill="${C[line.role]}">${esc(line.text)}</text>`
    })
    .join('\n')

  const support = CONTENT.support
    .map((line, i) => {
      const y = size.support.firstBaseline + i * size.support.lineHeight
      return `    <text class="support" x="${margin}" y="${y}" fill="${C.support}">${esc(line)}</text>`
    })
    .join('\n')

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(CONTENT.headline.map((l) => l.text).join(' '))}">
  <title>Grainlify — ${size.platform} share card</title>
${GENERATED_BY}
  <style>
    ${FONT_IMPORT}
    text { font-family: ${FONT_STACK}; }
    .wordmark { font-size: ${size.wordmarkSize}px; font-weight: 600; letter-spacing: -0.01em; }
    .headline { font-size: ${size.headline.size}px; font-weight: 700; letter-spacing: -0.022em; }
    .support  { font-size: ${size.support.size}px; font-weight: 400; letter-spacing: 0; }
    .footer   { font-size: ${size.footer.size}px; font-weight: 600; letter-spacing: 0.01em; }
  </style>

  <rect data-decorative="true" width="${width}" height="${height}" fill="${C.ground}"/>

  <g>
${lockup({
    x: margin,
    y: margin,
    logoSize: size.logoSize,
    wordmarkSize: size.wordmarkSize,
    markFill: C.gold,
    wordFill: C.cream,
  })}

${headline}

${support}

    <text class="footer" x="${margin}" y="${size.footer.baseline}" fill="${C.gold}">${esc(CONTENT.footer)}</text>
  </g>
</svg>
`
}

function cardContrastPairs() {
  const pairs = []
  for (const size of SIZES) {
    pairs.push({ what: `${size.name}: wordmark`, fg: C.cream, bg: C.ground, px: size.wordmarkSize, bold: true })
    for (const line of CONTENT.headline) {
      pairs.push({
        what: `${size.name}: headline "${line.text.slice(0, 26)}"`,
        fg: C[line.role],
        bg: C.ground,
        px: size.headline.size,
        bold: true,
      })
    }
    pairs.push({ what: `${size.name}: supporting line`, fg: C.support, bg: C.ground, px: size.support.size, bold: false })
    pairs.push({ what: `${size.name}: footer`, fg: C.gold, bg: C.ground, px: size.footer.size, bold: false })
    pairs.push({ what: `${size.name}: logo mark`, fg: C.gold, bg: C.ground, px: size.logoSize, graphic: true })
  }
  return pairs
}

// ===========================================================================
// 2. Banners
// ===========================================================================

/**
 * The lightest ground any text on this banner can land on: the base colour
 * with every texture layer flattened onto it. Contrast is audited against this
 * rather than against the flat ground, because a dot under a letter is part of
 * that letter's background whether or not it was drawn as decoration.
 */
function worstBg(b) {
  const layers = []
  if (b.texture?.ghost) layers.push({ colour: C.gold, alpha: b.texture.ghost.opacity })
  if (b.texture) layers.push({ colour: C.gold, alpha: b.texture.opacity })
  return compositeOver(C.ground, layers)
}

function textureMarkup(b) {
  if (!b.texture) return ''
  const { spacing, radius, opacity, ghost } = b.texture
  const half = spacing / 2

  // A half-drop tile: two dots per cell puts the lattice on the diagonal
  // without drawing any lines, which is the "sparse" reading rather than the
  // "graph paper" one.
  const pattern = `    <pattern id="dots" width="${spacing}" height="${spacing}" patternUnits="userSpaceOnUse">
      <circle cx="${half / 2}" cy="${half / 2}" r="${radius}" fill="${C.gold}" fill-opacity="${opacity}"/>
      <circle cx="${half + half / 2}" cy="${half + half / 2}" r="${radius}" fill="${C.gold}" fill-opacity="${opacity}"/>
    </pattern>`

  let ghostMarkup = ''
  if (ghost) {
    const scale = ghost.height / logo.vbH
    const y = ghost.centreY - ghost.height / 2
    ghostMarkup = `
  <g transform="translate(${ghost.x}, ${y}) scale(${scale.toFixed(5)})" opacity="${ghost.opacity}">
    <!-- Valueless attributes are legal HTML but not legal XML, and an SVG is
         parsed as XML: writing this bare made the whole document fail to parse
         and render blank. -->
    <path data-decorative="true" d="${logo.path}" fill="${C.gold}"/>
  </g>`
  }

  return `  <defs>
${pattern}
  </defs>

  <rect data-decorative="true" width="${b.width}" height="${b.height}" fill="url(#dots)"/>${ghostMarkup}`
}

/**
 * The vertical rule beside the type. Deliberately NOT decorative: it is a
 * drawn element with a position, so it has to clear the avatar overlay and the
 * crop windows like everything else. Marking it decorative to skip the check
 * would be marking it as "allowed to be covered", which it is not.
 */
function accentMarkup(b) {
  if (!b.accent) return ''
  const { x, width, top, bottom } = b.accent
  return `
    <rect x="${x}" y="${top}" width="${width}" height="${bottom - top}" rx="${width / 2}" fill="${C.gold}"/>`
}

function buildBannerSvg(b) {
  const { width, height } = b
  const label = `Grainlify. ${BANNER_CONTENT.lead} ${BANNER_CONTENT.hero}`

  const lockupMarkup = b.showLockup
    ? `\n${lockup({
        x: b.contentX,
        y: b.markTop,
        logoSize: b.logoSize,
        wordmarkSize: b.wordmarkSize,
        markFill: C.gold,
        wordFill: C.cream,
        gap: Math.round(b.logoSize * 0.4),
      })}\n`
    : ''

  const wordmarkRule = b.showLockup
    ? `\n    .wordmark { font-size: ${b.wordmarkSize}px; font-weight: 600; letter-spacing: -0.01em; }`
    : ''

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(label)}">
  <title>Grainlify — ${b.platform} banner</title>
${GENERATED_BY}
  <style>
    ${FONT_IMPORT}
    text { font-family: ${FONT_STACK}; }${wordmarkRule}
    .lead { font-size: ${b.lead.size}px; font-weight: 400; letter-spacing: 0; }
    .hero { font-size: ${b.hero.size}px; font-weight: 700; letter-spacing: -0.02em; }
  </style>

  <rect data-decorative="true" width="${width}" height="${height}" fill="${C.ground}"/>
${textureMarkup(b)}

  <g>${accentMarkup(b)}${lockupMarkup}
    <text class="lead" x="${b.contentX}" y="${b.lead.baseline}" fill="${C[b.lead.role]}">${esc(BANNER_CONTENT.lead)}</text>
    <text class="hero" x="${b.contentX}" y="${b.hero.baseline}" fill="${C[b.hero.role]}">${esc(BANNER_CONTENT.hero)}</text>
  </g>
</svg>
`
}

function bannerContrastPairs() {
  return BANNERS.flatMap((b) => {
    const bg = worstBg(b)
    const pairs = [
      { what: `${b.name} banner: lead line`, fg: C[b.lead.role], bg, px: b.lead.size, bold: false },
      { what: `${b.name} banner: hero line`, fg: C[b.hero.role], bg, px: b.hero.size, bold: true },
    ]
    if (b.accent) {
      pairs.push({ what: `${b.name} banner: accent rule`, fg: C.gold, bg, px: b.accent.width, graphic: true })
    }
    if (b.showLockup) {
      pairs.push(
        { what: `${b.name} banner: wordmark`, fg: C.cream, bg, px: b.wordmarkSize, bold: true },
        { what: `${b.name} banner: logo mark`, fg: C.gold, bg, px: b.logoSize, graphic: true },
      )
    }
    return pairs
  })
}

/**
 * The check the brief turns on: nothing may sit under the profile picture.
 *
 * The zone is anchored bottom-left because that is where both platforms put
 * the overlay. An element counts as violating if its box intersects the zone
 * at all - "mostly clear" is still partly covered.
 */
function bannerProblems(b, boxes) {
  const problems = []
  const zoneRight = b.avatarZone.width
  const zoneTop = b.height - b.avatarZone.height
  const safeRight = b.width - b.marginRight
  const safeBottom = b.height - b.marginTop

  for (const el of boxes) {
    const label = `${b.name} banner: ${el.kind === 'path' ? 'logo mark' : `"${el.label}"`}`
    if (el.left < zoneRight && el.bottom > zoneTop) {
      problems.push(
        `${label} intersects the profile-picture overlay ` +
          `(left ${el.left} < ${zoneRight}, bottom ${el.bottom} > ${zoneTop})`,
      )
    }
    if (el.right > safeRight) problems.push(`${label} ends at ${el.right}px, past the ${safeRight}px safe edge`)
    if (el.top < b.marginTop) problems.push(`${label} starts at ${el.top}px, above the ${b.marginTop}px margin`)
    if (el.bottom > safeBottom) problems.push(`${label} reaches ${el.bottom}px, below the ${safeBottom}px safe edge`)

    // Every crop window, not just the full canvas. This is what catches a
    // layout that is correct on desktop and loses a word on mobile.
    for (const crop of b.crops ?? []) {
      if (el.left < crop.left || el.right > crop.right) {
        problems.push(
          `${label} spans ${el.left}-${el.right}px, outside the ${crop.name} crop ` +
            `(${crop.left}-${crop.right}px)`,
        )
      }
      if (el.top < crop.top || el.bottom > crop.bottom) {
        problems.push(
          `${label} spans ${el.top}-${el.bottom}px vertically, outside the ${crop.name} crop ` +
            `(${crop.top}-${crop.bottom}px)`,
        )
      }
    }
  }
  return problems
}

// ===========================================================================
// 3. Early-access campaign card
// ===========================================================================

function buildCampaignSvg(c) {
  const { width, height, margin } = c

  const suffix = CAMPAIGN_CONTENT.displaySuffix
    .map((word, i) => {
      const y = c.displaySuffix.firstBaseline + i * c.displaySuffix.lineHeight
      return `    <text class="suffix" x="${c.displaySuffix.x}" y="${y}" fill="${C[c.displaySuffix.role]}">${esc(word)}</text>`
    })
    .join('\n')

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(`${CAMPAIGN_CONTENT.display} ${CAMPAIGN_CONTENT.displaySuffix.join(' ')}. ${CAMPAIGN_CONTENT.lead} ${CAMPAIGN_CONTENT.support}`)}">
  <title>Grainlify — ${c.platform} early-access card</title>
${GENERATED_BY}
  <style>
    ${FONT_IMPORT}
    text { font-family: ${FONT_STACK}; }
    .wordmark { font-size: ${c.wordmarkSize}px; font-weight: 600; letter-spacing: -0.01em; }
    /* Tight tracking is what makes three digits read as one object rather
       than as three characters that happen to be adjacent. */
    .display  { font-size: ${c.display.size}px; font-weight: 700; letter-spacing: -0.045em; }
    .suffix   { font-size: ${c.displaySuffix.size}px; font-weight: 700; letter-spacing: -0.02em; }
    .lead     { font-size: ${c.lead.size}px; font-weight: 600; letter-spacing: -0.01em; }
    .support  { font-size: ${c.support.size}px; font-weight: 400; letter-spacing: 0; }
    .footer   { font-size: ${c.footer.size}px; font-weight: 600; letter-spacing: 0.01em; }
  </style>

  <rect data-decorative="true" width="${width}" height="${height}" fill="${C.ground}"/>
${textureMarkup(c)}

  <g>
${lockup({
    x: margin,
    y: margin,
    logoSize: c.logoSize,
    wordmarkSize: c.wordmarkSize,
    markFill: C.gold,
    wordFill: C.cream,
  })}

    <text class="display" x="${margin}" y="${c.display.baseline}" fill="${C[c.display.role]}">${esc(CAMPAIGN_CONTENT.display)}</text>
${suffix}

    <text class="lead" x="${margin}" y="${c.lead.baseline}" fill="${C[c.lead.role]}">${esc(CAMPAIGN_CONTENT.lead)}</text>
    <text class="support" x="${margin}" y="${c.support.baseline}" fill="${C[c.support.role]}">${esc(CAMPAIGN_CONTENT.support)}</text>
    <text class="footer" x="${margin}" y="${c.footer.baseline}" fill="${C[c.footer.role]}">${esc(CAMPAIGN_CONTENT.footer)}</text>
  </g>
</svg>
`
}

function campaignContrastPairs() {
  return CAMPAIGNS.flatMap((c) => {
    const bg = worstBg(c)
    return [
      { what: `${c.name} campaign: "300" display`, fg: C[c.display.role], bg, px: c.display.size, bold: true },
      { what: `${c.name} campaign: "founding spots"`, fg: C[c.displaySuffix.role], bg, px: c.displaySuffix.size, bold: true },
      { what: `${c.name} campaign: lead line`, fg: C[c.lead.role], bg, px: c.lead.size, bold: true },
      { what: `${c.name} campaign: supporting line`, fg: C[c.support.role], bg, px: c.support.size, bold: false },
      { what: `${c.name} campaign: footer`, fg: C[c.footer.role], bg, px: c.footer.size, bold: false },
      { what: `${c.name} campaign: logo mark`, fg: C.gold, bg, px: c.logoSize, graphic: true },
    ]
  })
}

/**
 * Legibility at the size the card is actually seen, measured from the pixels
 * of the thumbnail itself.
 *
 * A text element's bounding box is the font's em box - ascent plus descent,
 * about 1.21em - not the visible glyphs. For "300" at 240px that box is 291px
 * tall while the digits are nearer 174, so checking the box would overstate
 * the number by two thirds and could pass a card whose digits had actually
 * gone to mush. This reads the rendered PNG and finds the rows that actually
 * contain the display colour.
 *
 * The scan window is derived from measurements rather than guessed: it starts
 * below the logo mark, which is the same yellow and shares the number's
 * x-range, and it reports rather than silently trusts a window that clipped
 * the ink it was supposed to contain.
 */
async function measureDisplayInk(c, boxes, thumbPath) {
  const scale = c.thumbnail.width / c.width
  const display = boxes.find((b) => b.cls === 'display')
  const mark = boxes.find((b) => b.kind === 'path')
  if (!display) return { problems: [`${c.name} campaign: no display number to measure`] }

  const x0 = Math.round(display.left * scale)
  const x1 = Math.round(display.right * scale)
  // Exclude the lockup: it is the same colour and sits directly above.
  const yTop = Math.max(display.top, (mark?.bottom ?? 0) + 2)
  const y0 = Math.round(yTop * scale)
  const y1 = Math.round(display.bottom * scale)

  const { data, info } = await sharp(thumbPath).raw().toBuffer({ resolveWithObject: true })
  const target = [1, 3, 5].map((i) => parseInt(C.gold.slice(i, i + 2), 16))
  const near = (i) =>
    Math.abs(data[i] - target[0]) < 40 &&
    Math.abs(data[i + 1] - target[1]) < 40 &&
    Math.abs(data[i + 2] - target[2]) < 40

  let inkTop = null
  let inkBottom = null
  for (let y = y0; y < Math.min(y1, info.height); y++) {
    let hit = false
    for (let x = Math.max(0, x0); x < Math.min(x1, info.width); x++) {
      if (near((y * info.width + x) * info.channels)) {
        hit = true
        break
      }
    }
    if (hit) {
      if (inkTop === null) inkTop = y
      inkBottom = y
    }
  }

  const problems = []
  if (inkTop === null) {
    problems.push(`${c.name} campaign: found no display-coloured pixels in the thumbnail`)
    return { problems }
  }
  if (inkTop <= y0) {
    problems.push(
      `${c.name} campaign: the display ink reaches the top of the scan window (${y0}px), ` +
        `so the measurement may be clipped or catching the lockup`,
    )
  }

  const inkPx = inkBottom - inkTop + 1
  if (inkPx < c.thumbnail.minDisplayPx) {
    problems.push(
      `${c.name} campaign: "${display.label}" renders ${inkPx}px of actual ink at ` +
        `${c.thumbnail.width}px wide, under the ${c.thumbnail.minDisplayPx}px legibility floor`,
    )
  }
  return { problems, inkPx, boxPx: Math.round((display.bottom - display.top) * scale) }
}

/** The numeral's width is the font's business, not ours, so the gap beside it
 *  is measured rather than trusted. */
function campaignGapProblems(c, boxes) {
  const display = boxes.find((b) => b.cls === 'display')
  const suffix = boxes.filter((b) => b.cls === 'suffix')
  if (!display || !suffix.length) return [`${c.name} campaign: could not measure the display pairing`]

  const gap = Math.min(...suffix.map((s) => s.left)) - display.right
  if (gap < c.suffixGap.min || gap > c.suffixGap.max) {
    return [
      `${c.name} campaign: "founding spots" sits ${gap}px from "${display.label}", ` +
        `outside the ${c.suffixGap.min}-${c.suffixGap.max}px range`,
    ]
  }
  return []
}

// ===========================================================================
// 4. Avatars
// ===========================================================================

/**
 * The mark's PAINTED bounds, in viewBox units.
 *
 * Centring on the viewBox instead would centre the padding: the source asset's
 * box is 28.77 x 26.33 while the glyph inside it is neither centred nor
 * flush, so a "centred" avatar built from the viewBox sits visibly off. Probed
 * at 10x so rounding to whole device pixels is negligible.
 */
async function measureInk(browser) {
  const S = 10
  const probe = path.join(outDir, '.ink-probe.svg')
  writeFileSync(
    probe,
    `<svg xmlns="http://www.w3.org/2000/svg" width="${logo.vbW * S}" height="${logo.vbH * S}" viewBox="0 0 ${logo.vbW} ${logo.vbH}"><path d="${logo.path}" fill="#000"/></svg>`,
  )
  const { boxes } = await renderOne(browser, {
    svgPath: probe,
    pngPath: null,
    width: Math.ceil(logo.vbW * S),
    height: Math.ceil(logo.vbH * S),
    scale: 1,
  })
  rmSync(probe, { force: true })

  const p = boxes.find((b) => b.kind === 'path')
  if (!p) throw new Error('avatar: could not measure the mark')
  return { x: p.left / S, y: p.top / S, w: (p.right - p.left) / S, h: (p.bottom - p.top) / S }
}

function buildAvatarSvg(variant, ink) {
  const { size, markHeight } = AVATARS
  const centre = size / 2
  const scale = markHeight / ink.h
  // Map the ink's centre onto the canvas centre: tx + scale*inkCentre = centre.
  const tx = centre - scale * (ink.x + ink.w / 2)
  const ty = centre - scale * (ink.y + ink.h / 2)

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" role="img" aria-label="Grainlify">
  <title>Grainlify — profile picture (${variant.name})</title>
${GENERATED_BY}
  <rect data-decorative="true" width="${size}" height="${size}" fill="${C[variant.ground]}"/>
  <g transform="translate(${tx.toFixed(3)}, ${ty.toFixed(3)}) scale(${scale.toFixed(5)})">
    <path d="${logo.path}" fill="${C[variant.mark]}"/>
  </g>
</svg>
`
}

/**
 * X crops the avatar to a circle. The mark has to sit inside the inscribed
 * circle with clearance, so the test is radial - the furthest corner of the
 * mark's box from the centre, not its left/right edges. A square-margin check
 * passes marks that get clipped on the diagonal.
 */
function avatarProblems(variant, boxes) {
  const centre = AVATARS.size / 2
  const mark = boxes.find((b) => b.kind === 'path')
  if (!mark) return [`${variant.name}: the mark did not render`]

  const corners = [
    [mark.left, mark.top],
    [mark.right, mark.top],
    [mark.left, mark.bottom],
    [mark.right, mark.bottom],
  ]
  const furthest = Math.max(...corners.map(([x, y]) => Math.hypot(x - centre, y - centre)))
  if (furthest > AVATARS.safeRadius) {
    return [
      `${variant.name}: the mark reaches ${furthest.toFixed(1)}px from centre, ` +
        `past the ${AVATARS.safeRadius}px safe radius — the circular crop would clip it`,
    ]
  }

  const offX = (mark.left + mark.right) / 2 - centre
  const offY = (mark.top + mark.bottom) / 2 - centre
  if (Math.abs(offX) > 1 || Math.abs(offY) > 1) {
    return [`${variant.name}: the mark is off-centre by (${offX.toFixed(1)}, ${offY.toFixed(1)})px`]
  }
  return []
}

// ===========================================================================
// Build
// ===========================================================================

auditContrast(cardContrastPairs(), 'share cards')
auditContrast(bannerContrastPairs(), 'banners')
auditContrast(campaignContrastPairs(), 'campaign cards')
auditContrast(
  AVATARS.variants.map((v) => ({
    what: `avatar ${v.name}: mark`,
    fg: C[v.mark],
    bg: C[v.ground],
    px: AVATARS.markHeight,
    graphic: true,
  })),
  'avatars',
)

const browser = await chromium.launch()
const problems = []
const written = []

console.log(`\nRendering share cards`)
for (const size of SIZES) {
  const svgPath = path.join(outDir, `grainlify-launch-${size.name}.svg`)
  const pngPath = path.join(outDir, `grainlify-launch-${size.name}@2x.png`)
  writeFileSync(svgPath, buildCardSvg(size))
  const { boxes, usedInter } = await renderOne(browser, { svgPath, pngPath, ...size })

  const safeRight = size.width - size.margin
  const safeBottom = size.height - size.margin
  for (const el of boxes) {
    const label = `${size.name} card: ${el.kind === 'path' ? 'logo mark' : `"${el.label}"`}`
    if (el.right > safeRight) problems.push(`${label} ends at ${el.right}px, past the ${safeRight}px safe edge`)
    if (el.left < size.margin) problems.push(`${label} starts at ${el.left}px, inside the ${size.margin}px margin`)
    if (el.bottom > safeBottom) problems.push(`${label} reaches ${el.bottom}px, below the ${safeBottom}px safe edge`)
  }
  const widest = Math.max(...boxes.map((b) => b.right))
  console.log(
    `  ${size.name.padEnd(9)} ${size.width}x${size.height} -> ${size.width * 2}x${size.height * 2}` +
      `  widest ${widest}/${safeRight}px  font ${usedInter ? 'Inter' : 'FALLBACK'}`,
  )
  written.push(svgPath, pngPath)
}

console.log(`\nRendering campaign cards`)
for (const c of CAMPAIGNS) {
  const svgPath = path.join(outDir, `grainlify-early-access-${c.name}.svg`)
  const pngPath = path.join(outDir, `grainlify-early-access-${c.name}@2x.png`)
  const thumbPath = path.join(outDir, `grainlify-early-access-${c.name}-thumb.png`)
  writeFileSync(svgPath, buildCampaignSvg(c))

  const { boxes, usedInter } = await renderOne(browser, {
    svgPath,
    pngPath,
    width: c.width,
    height: c.height,
  })

  const safeRight = c.width - c.margin
  const safeBottom = c.height - c.margin
  for (const el of boxes) {
    const label = `${c.name} campaign: ${el.kind === 'path' ? 'logo mark' : `"${el.label}"`}`
    if (el.right > safeRight) problems.push(`${label} ends at ${el.right}px, past the ${safeRight}px safe edge`)
    if (el.left < c.margin) problems.push(`${label} starts at ${el.left}px, inside the ${c.margin}px margin`)
    if (el.bottom > safeBottom) problems.push(`${label} reaches ${el.bottom}px, below the ${safeBottom}px safe edge`)
  }
  problems.push(...campaignGapProblems(c, boxes))

  // Second render at feed-thumbnail width. deviceScaleFactor scales the raster
  // while leaving the CSS-pixel geometry alone, so the same boxes describe both
  // renders and the thumbnail size is the box times the ratio.
  const thumbScale = c.thumbnail.width / c.width
  await renderOne(browser, {
    svgPath,
    pngPath: thumbPath,
    width: c.width,
    height: c.height,
    scale: thumbScale,
  })
  const ink = await measureDisplayInk(c, boxes, thumbPath)
  problems.push(...ink.problems)

  const display = boxes.find((b) => b.cls === 'display')
  const suffixLeft = Math.min(...boxes.filter((b) => b.cls === 'suffix').map((b) => b.left))
  console.log(
    `  ${c.name.padEnd(9)} ${c.width}x${c.height} -> ${c.width * 2}x${c.height * 2}` +
      `  widest ${Math.max(...boxes.map((b) => b.right))}/${safeRight}px  font ${usedInter ? 'Inter' : 'FALLBACK'}`,
  )
  console.log(
    `      "${display.label}" ${suffixLeft - display.right}px from "founding spots" ` +
      `(allowed ${c.suffixGap.min}-${c.suffixGap.max}px)`,
  )
  console.log(
    `      thumbnail ${c.thumbnail.width}x${Math.round(c.height * thumbScale)}: ` +
      `"${display.label}" measures ${ink.inkPx}px of real ink ` +
      `(em box would have claimed ${ink.boxPx}px) / ${c.thumbnail.minDisplayPx}px floor`,
  )
  written.push(svgPath, pngPath, thumbPath)
}

console.log(`\nRendering banners`)
for (const b of BANNERS) {
  const svgPath = path.join(outDir, `grainlify-banner-${b.name}.svg`)
  const pngPath = path.join(outDir, `grainlify-banner-${b.name}@2x.png`)
  writeFileSync(svgPath, buildBannerSvg(b))
  const { boxes, usedInter } = await renderOne(browser, { svgPath, pngPath, width: b.width, height: b.height })

  problems.push(...bannerProblems(b, boxes))
  const left = Math.min(...boxes.map((x) => x.left))
  const right = Math.max(...boxes.map((x) => x.right))
  const top = Math.min(...boxes.map((x) => x.top))
  const bottom = Math.max(...boxes.map((x) => x.bottom))
  console.log(
    `  ${b.name.padEnd(9)} ${b.width}x${b.height} -> ${b.width * 2}x${b.height * 2}  ` +
      `content x ${left}-${right}, y ${top}-${bottom}  ` +
      `clears ${b.avatarZone.width}px avatar zone  font ${usedInter ? 'Inter' : 'FALLBACK'}`,
  )
  // Named explicitly so "both crops were verified" is visible in the output
  // rather than something you have to read the source to believe.
  for (const crop of b.crops ?? []) {
    console.log(
      `      ${crop.name.padEnd(8)} crop x ${crop.left}-${crop.right}, y ${crop.top}-${crop.bottom}  ` +
        `-> fits with ${left - crop.left}px left, ${crop.right - right}px right, ` +
        `${top - crop.top}px top, ${crop.bottom - bottom}px bottom to spare`,
    )
  }
  written.push(svgPath, pngPath)
}

console.log(`\nRendering avatars`)
const ink = await measureInk(browser)
console.log(
  `  mark ink measured at ${ink.w.toFixed(2)}x${ink.h.toFixed(2)} in a ${logo.vbW}x${logo.vbH} viewBox` +
    ` (offset ${ink.x.toFixed(2)}, ${ink.y.toFixed(2)}) — centred on the ink, not the box`,
)
for (const variant of AVATARS.variants) {
  const svgPath = path.join(outDir, `grainlify-avatar-${variant.name}.svg`)
  const pngPath = path.join(outDir, `grainlify-avatar-${variant.name}.png`)
  const png2xPath = path.join(outDir, `grainlify-avatar-${variant.name}@2x.png`)
  writeFileSync(svgPath, buildAvatarSvg(variant, ink))

  // 400x400 is the size the platforms ask for; the 2x is for anywhere that
  // wants a denser source.
  const { boxes } = await renderOne(browser, {
    svgPath,
    pngPath,
    width: AVATARS.size,
    height: AVATARS.size,
    scale: 1,
  })
  await renderOne(browser, {
    svgPath,
    pngPath: png2xPath,
    width: AVATARS.size,
    height: AVATARS.size,
    scale: 2,
  })

  problems.push(...avatarProblems(variant, boxes))
  const mark = boxes.find((x) => x.kind === 'path')
  const furthest = Math.max(
    ...[
      [mark.left, mark.top],
      [mark.right, mark.top],
      [mark.left, mark.bottom],
      [mark.right, mark.bottom],
    ].map(([x, y]) => Math.hypot(x - AVATARS.size / 2, y - AVATARS.size / 2)),
  )
  console.log(
    `  ${variant.name.padEnd(13)} ${AVATARS.size}x${AVATARS.size} + @2x` +
      `  mark reaches ${furthest.toFixed(1)}px from centre / ${AVATARS.safeRadius}px safe radius`,
  )
  written.push(svgPath, pngPath, png2xPath)
}

await browser.close()

if (
  reportProblems(
    problems,
    `Text past a safe edge disappears when the platform crops. Text under the avatar ` +
      `zone is covered outright. Adjust the geometry in content.mjs.`,
  )
) {
  process.exit(1)
}

console.log(`\nWrote ${written.length} files to assets/social/`)
for (const f of written) console.log(`  ${path.relative(repoRoot, f)}`)
